// Single source of truth for everything on the page.
// Edit here; the DOM is generated from this in ui.js.

export const profile = {
  name: "Lara Chieppe",
  role: "Software & ML Engineer",
  location: "Berkeley, CA",
  tagline: [
    "I build systems that",
    "reason over messy data",
  ],
  blurb:
    "Bioengineering at UC Berkeley, but most of my time goes to shipping software — " +
    "payment infrastructure at BTG Pactual, React Native products for fintech teams, and " +
    "ML systems that I hold to real, measured numbers. I care about the boring parts: " +
    "latency budgets, evaluation harnesses, and never reporting an accuracy I did not measure.",
  email: "larachieppe@berkeley.edu",
  phone: "+1 (510) 993-6443",
  links: [
    { label: "GitHub", href: "https://github.com/larachieppe", handle: "larachieppe" },
    { label: "LinkedIn", href: "https://linkedin.com/in/larachieppe", handle: "in/larachieppe" },
    { label: "Email", href: "mailto:larachieppe@berkeley.edu", handle: "larachieppe@berkeley.edu" },
  ],
};

export const education = {
  school: "University of California, Berkeley",
  degree: "B.S. Bioengineering",
  dates: "Aug 2023 — May 2027",
  detail:
    "Data Structures & Algorithms · Full Stack Web Development · Machine Structures · " +
    "Efficient Algorithms · Probability Theory · Cybersecurity · Networking",
};

export const projects = [
  {
    id: "research-lab-assistant",
    title: "Research Lab Assistant",
    kicker: "Multi-agent literature synthesis",
    year: "2026",
    stack: ["Python", "LangGraph", "Claude API", "FastAPI", "PostgreSQL"],
    summary:
      "A five-stage LangGraph pipeline that retrieves real papers from PubMed and arXiv, " +
      "screens them before spending money on extraction, and returns a fully cited answer. " +
      "Citations are assembled deterministically, never generated by the model, so they cannot drift.",
    metrics: [
      { value: "61%", label: "fewer LLM extraction calls" },
      { value: "$0.06", label: "per query, 20+ papers" },
      { value: "~25s", label: "end-to-end synthesis" },
    ],
    href: "https://research-lab-assistant.onrender.com/",
    repo: "https://github.com/larachieppe/research-lab-assistant",
  },
  {
    id: "recall-tutor",
    title: "Recall",
    kicker: "Adaptive active-recall tutor",
    year: "2026",
    stack: ["TypeScript", "Next.js", "Claude API", "Drizzle", "PostgreSQL"],
    summary:
      "Turns lectures, papers, PDFs and YouTube transcripts into free-response practice with " +
      "rubric-grounded feedback — graded criterion by criterion, not by wording match. " +
      "Spaced repetition, mastery tracking, and an evaluation harness that reports only real numbers.",
    metrics: [
      { value: "~44%", label: "cheaper document reads" },
      { value: "0 calls", label: "to grade MC + flashcards" },
      { value: "75+", label: "unit tests, CI green" },
    ],
    href: "https://recall-tutor.onrender.com",
    repo: "https://github.com/larachieppe/recall-tutor",
  },
  {
    id: "protein-function-classifier",
    title: "Protein Localization Classifier",
    kicker: "Protein language models, measured honestly",
    year: "2026",
    stack: ["PyTorch", "ESM-2", "HuggingFace", "UMAP", "scikit-learn"],
    summary:
      "Predicts where a protein lives in the cell from its amino-acid sequence alone. " +
      "Started from a frozen-embedding probe and worked up to a fine-tuned 650M-parameter " +
      "ESM-2 with attention pooling — every number on the dashboard is one I actually measured.",
    metrics: [
      { value: "81.1%", label: "10-class accuracy, from 64.9%" },
      { value: "87%", label: "on the 4-class regrouping" },
      { value: "650M", label: "params, attention-pooled" },
    ],
    href: "https://larachieppe.github.io/protein-function-classifier/",
    repo: "https://github.com/larachieppe/protein-function-classifier",
  },
  {
    id: "on-device-triage",
    title: "On-Device Triage Assistant",
    kicker: "A small model in the browser, an LLM only when needed",
    year: "2026",
    stack: ["ONNX Runtime Web", "Transformers", "Claude API", "FastAPI"],
    summary:
      "A distilled transformer exported to ONNX and run entirely in the browser, with a " +
      "server-side model as fallback only when the local one is not confident. " +
      "The project is about the cost and latency tradeoff between the two, not the medical claim.",
    metrics: [
      { value: "0¢", label: "per on-device inference" },
      { value: "local", label: "first, API second" },
    ],
    repo: "https://github.com/larachieppe",
  },
  {
    id: "model-regression-detector",
    title: "Model Regression Detector",
    kicker: "CI/CD for prompt changes",
    year: "2026",
    stack: ["Python", "pytest", "YAML configs"],
    summary:
      "Runs a golden dataset against a versioned prompt config, scores outputs on multiple " +
      "dimensions, and diffs each run against the last baseline — so a prompt edit that quietly " +
      "degrades quality gets caught before it merges.",
    metrics: [
      { value: "golden", label: "dataset diffing" },
      { value: "v1 → v2", label: "prompt versioning" },
    ],
    repo: "https://github.com/larachieppe",
  },
];

export const experience = [
  {
    company: "Reach Capital",
    role: "Product Manager & Software Engineer (Contract)",
    dates: "Aug 2025 — Present",
    place: "Berkeley, CA",
    stack: "SQL · Supabase · React",
    points: [
      "Engineered infrastructure empowering 130+ partner companies to analyze student applications.",
      "Developed dynamic, parameterized SQL filters and optimized Supabase schema design, cutting latency by 45%.",
      "Directed a team of 6 through 5+ sprints, delivering 5 production releases and launching 10 features.",
    ],
  },
  {
    company: "BTG Pactual",
    role: "Software Engineering Intern",
    dates: "Jan 2025 — Sept 2025",
    place: "São Paulo, Brazil",
    stack: "AWS · Kotlin · MongoDB",
    points: [
      "Optimized MongoDB aggregation queries for account filtering, reducing query latency by 50%.",
      "Built an AWS SNS → SQS pipeline automating fraud-signal delivery, enabling real-time revocation across 4 payment microservices.",
      "Streamlined account sign-in by detecting and reusing existing accounts, improving completion rate by 25%.",
    ],
  },
  {
    company: "Lafayette Square",
    role: "Product Manager & Software Engineer (Contract)",
    dates: "Jan 2025 — Sept 2025",
    place: "Berkeley, CA",
    stack: "AWS · MongoDB · React Native",
    points: [
      "Built and deployed a React Native app serving financial insights to 34+ client companies alongside the CEO and CTO.",
      "Led a cross-functional team of 10 through 10+ weeks of agile sprints, improving release cadence by 40%.",
      "Implemented dynamic parametrized queries delivering real-time, interactive data from AWS-hosted MongoDB.",
    ],
  },
  {
    company: "SUR",
    role: "Software Engineer (Contract)",
    dates: "Jan 2025 — Aug 2025",
    place: "Berkeley, CA",
    stack: "AWS · GraphQL · React Native",
    points: [
      "Developed and deployed a scalable car rental feature in a fleet management app serving 5,000+ users.",
      "Integrated GraphQL APIs with an AWS backend to streamline fleet inventory storage and retrieval.",
      "Reduced data query latency by 25% through GraphQL caching and AWS API Gateway optimization.",
    ],
  },
  {
    company: "UC Berkeley EECS",
    role: "Teaching Intern — Data Structures & Algorithms (CS61B)",
    dates: "Aug 2024 — Dec 2024",
    place: "Berkeley, CA",
    stack: "Java",
    points: [
      "One of 20 teaching interns supporting 1,500+ students.",
      "Guided students through object-oriented programming, algorithms and data structures in Java.",
      "Resolved 50+ student tickets covering asymptotics, sorting, hashing and percolation simulations.",
    ],
  },
];

export const skills = [
  {
    group: "Languages",
    items: ["Python", "Java", "Kotlin", "TypeScript", "JavaScript", "C", "C++", "C#", "SQL", "GraphQL"],
  },
  {
    group: "AI / ML",
    items: ["PyTorch", "HuggingFace", "Transformers", "LangGraph", "Claude API", "scikit-learn", "Pandas", "NumPy", "Matplotlib"],
  },
  {
    group: "Frameworks",
    items: ["React Native", "Next.js", "Node.js", "Express.js", "FastAPI", "Redux"],
  },
  {
    group: "Infrastructure",
    items: ["AWS (S3, SNS, SQS, Lambda, API Gateway)", "PostgreSQL", "MongoDB", "DynamoDB", "Drizzle", "Git", "Postman"],
  },
  {
    group: "Spoken",
    items: ["English (fluent)", "Portuguese (native)", "German (B2)", "Spanish (B2)"],
  },
];

// Section registry — drives the side rail and the 3D morph targets.
export const sections = [
  { id: "hero", label: "Index", shape: "helix" },
  { id: "about", label: "About", shape: "helix" },
  { id: "work", label: "Work", shape: "lattice" },
  { id: "experience", label: "Experience", shape: "lattice" },
  { id: "skills", label: "Skills", shape: "globe" },
  { id: "contact", label: "Contact", shape: "globe" },
];
