// Single source of truth for everything on the page.
// Edit here; the DOM is generated from this in ui.js.

export const profile = {
  name: "Lara Chieppe",
  role: "Software & ML Engineer",
  location: "Berkeley, CA",
  tagline: [
    "I build systems that",
    "reason over messy data",
  ],
  blurb:
    "I care about the parts that don’t demo well — latency budgets, evaluation harnesses, " +
    "deterministic tests — and I’d rather report a number I actually measured than one that " +
    "sounds impressive. Most of what I build has to survive contact with real, messy data, so " +
    "I hold it to results I can reproduce.",
  email: "larachieppe@berkeley.edu",
  phone: "+1 (510) 993-6443",
  links: [
    { label: "GitHub", href: "https://github.com/larachieppe", handle: "larachieppe" },
    { label: "LinkedIn", href: "https://linkedin.com/in/larachieppe", handle: "in/larachieppe" },
    { label: "Email", href: "mailto:larachieppe@berkeley.edu", handle: "larachieppe@berkeley.edu" },
  ],
};

export const education = {
  school: "University of California, Berkeley",
  degree: "B.S. Candidate · Class of 2027",
  dates: "Aug 2023 — May 2027",
  detail:
    "Data Structures & Algorithms · Full Stack Web Development · Machine Structures · " +
    "Efficient Algorithms · Probability Theory · Cybersecurity · Networking",
};

export const projects = [
  {
    id: "research-lab-assistant",
    title: "Research Lab Assistant",
    kicker: "Multi-agent literature synthesis",
    year: "2026",
    stack: ["Python", "LangGraph", "Claude API", "FastAPI", "PostgreSQL"],
    summary:
      "A five-stage LangGraph pipeline that retrieves real papers from PubMed and arXiv, " +
      "screens them before spending money on extraction, and returns a fully cited answer. " +
      "Citations are assembled deterministically, never generated by the model, so they cannot drift.",
    metrics: [
      { value: "61%", label: "fewer LLM extraction calls" },
      { value: "$0.06", label: "per query, 20+ papers" },
      { value: "~25s", label: "end-to-end synthesis" },
    ],
    href: "https://research-lab-assistant.onrender.com/",
    repo: "https://github.com/larachieppe/research-lab-assistant",
    caseStudy: {
      problem:
        "Ask an LLM a research question directly and you get a fluent-sounding answer with no " +
        "way to check it. I wanted the opposite of a prompt wrapper: real retrieval from the " +
        "literature, citations that can't drift from their sources, and tight cost control.",
      flow: [
        { label: "Question", sub: "natural language" },
        { label: "Retrieve", sub: "PubMed + arXiv" },
        { label: "Screen", sub: "relevance filter" },
        { label: "Extract", sub: "per-paper findings" },
        { label: "Synthesize", sub: "cited answer" },
      ],
      decision: {
        title: "Deterministic citations + screen-before-you-spend",
        body:
          "Citations are assembled deterministically from the retrieved source list — never " +
          "generated by the model — so they can't hallucinate or drift. And every paper is " +
          "screened for relevance before the pipeline pays to extract from it, which cut LLM " +
          "extraction calls by 61%. Retracted papers and unreviewed preprints are flagged, not hidden.",
      },
      result:
        "A fully cited answer over 20+ papers in ~25 seconds for about $0.06 a query, " +
        "orchestrated as five concurrent-capable LangGraph stages with hardened output " +
        "(injected-XSS sanitized, CSP/secure-cookie headers, rate-limited endpoints).",
    },
  },
  {
    id: "recall-tutor",
    title: "Recall",
    kicker: "Adaptive active-recall tutor",
    year: "2026",
    stack: ["TypeScript", "Next.js", "Claude API", "Drizzle", "PostgreSQL"],
    summary:
      "Turns lectures, papers, PDFs and YouTube transcripts into free-response practice with " +
      "rubric-grounded feedback — graded criterion by criterion, not by wording match. " +
      "Spaced repetition, mastery tracking, and an evaluation harness that reports only real numbers.",
    metrics: [
      { value: "~44%", label: "cheaper document reads" },
      { value: "0 calls", label: "to grade MC + flashcards" },
      { value: "75+", label: "unit tests, CI green" },
    ],
    href: "https://recall-tutor.onrender.com",
    repo: "https://github.com/larachieppe/recall-tutor",
    caseStudy: {
      problem:
        "Re-reading notes feels productive but barely builds recall. I wanted rubric-graded " +
        "free-response practice from any source — one that credits a valid paraphrase instead " +
        "of demanding exact wording, and that keeps API cost sane at scale.",
      flow: [
        { label: "Ingest", sub: "URL · PDF · YouTube · audio" },
        { label: "Chunk", sub: "whole-doc coverage" },
        { label: "Generate", sub: "grounded questions" },
        { label: "Grade", sub: "per rubric criterion" },
        { label: "Target", sub: "weakest concepts" },
      ],
      decision: {
        title: "Criterion-level grading + grade what you can for free",
        body:
          "Free-text answers are graded criterion by criterion against a rubric, with cited " +
          "evidence, so paraphrases get credit and unsupported claims get flagged. Multiple-choice " +
          "and flashcards are graded deterministically client-side — zero API calls. Prompt-caching " +
          "plus whole-document sampling instead of first-N-chars truncation cut document-read cost ~44%.",
      },
      result:
        "Multimodal ingestion, concept-mastery tracking with SM-2 spaced repetition, and a " +
        "grading-evaluation harness that reports only real, labeled numbers — backed by 75+ " +
        "passing unit tests in CI.",
    },
  },
  {
    id: "protein-function-classifier",
    title: "Protein Localization Classifier",
    kicker: "Protein language models, measured honestly",
    year: "2026",
    stack: ["PyTorch", "ESM-2", "HuggingFace", "UMAP", "scikit-learn"],
    summary:
      "Predicts where a protein lives in the cell from its amino-acid sequence alone. " +
      "Started from a frozen-embedding probe and worked up to a fine-tuned 650M-parameter " +
      "ESM-2 with attention pooling — every number on the dashboard is one I actually measured.",
    metrics: [
      { value: "81.1%", label: "10-class accuracy, from 64.9%" },
      { value: "87%", label: "on the 4-class regrouping" },
      { value: "650M", label: "params, attention-pooled" },
    ],
    href: "https://larachieppe.github.io/protein-function-classifier/",
    repo: "https://github.com/larachieppe/protein-function-classifier",
    caseStudy: {
      problem:
        "Predict a protein's subcellular location from its amino-acid sequence alone — and, just " +
        "as importantly, report only accuracy I actually measured. The project started by replacing " +
        "a scaffold whose impressive-sounding numbers turned out to be fabricated on synthetic data.",
      flow: [
        { label: "Sequence", sub: "amino acids" },
        { label: "ESM-2", sub: "650M embeddings" },
        { label: "Attention pool", sub: "over residues" },
        { label: "Classifier", sub: "10 compartments" },
      ],
      decision: {
        title: "Attention pooling over a single CLS token",
        body:
          "I worked up honestly from a frozen-embedding logistic probe (64.9%) rather than " +
          "starting from a headline number. The biggest single jump came from fine-tuning a 650M " +
          "ESM-2 and pooling the whole residue sequence with a learned attention head instead of " +
          "reading one CLS token — that took 10-class accuracy to 81.1%, at or above published " +
          "benchmarks for the task.",
      },
      result:
        "81.1% on the 10-class DeepLoc test set (up from a 64.9% baseline) and 87% on a 4-class " +
        "regrouping — every figure measured on held-out data, never on a filtered eval set.",
    },
  },
  {
    id: "on-device-triage",
    title: "On-Device Triage Assistant",
    kicker: "A small model in the browser, an LLM only when needed",
    year: "2026",
    stack: ["ONNX Runtime Web", "Transformers", "Claude API", "FastAPI"],
    summary:
      "A distilled transformer exported to ONNX and run entirely in the browser, with a " +
      "server-side model as fallback only when the local one is not confident. " +
      "The project is about the cost and latency tradeoff between the two, not the medical claim.",
    metrics: [
      { value: "0¢", label: "per on-device inference" },
      { value: "local", label: "first, API second" },
    ],
    repo: "https://github.com/larachieppe/on-device-triage-assistant",
    caseStudy: {
      problem:
        "Most ML demos just call an API. I wanted to show the actual systems tradeoff between a " +
        "small model running on the user's device and a large one behind an API — latency, cost, " +
        "and privacy — for a symptom-triage classifier.",
      decision: {
        title: "On-device first, escalate only on low confidence",
        body:
          "A distilled transformer is exported to ONNX and runs entirely in the browser via " +
          "onnxruntime-web — free and private. A confidence threshold routes only the uncertain " +
          "cases to a server-side Claude call, and a short clarifying-questions step runs before " +
          "any high-stakes or low-confidence verdict is shown.",
      },
      result:
        "Free, private inference for the common case; the paid API is spent only where it changes " +
        "the answer. (Portfolio demo — synthetic training data, not a medical product.)",
    },
  },
  {
    id: "model-regression-detector",
    title: "Model Regression Detector",
    kicker: "CI/CD for prompt changes",
    year: "2026",
    stack: ["Python", "pytest", "YAML configs"],
    summary:
      "Runs a golden dataset against a versioned prompt config, scores outputs on multiple " +
      "dimensions, and diffs each run against the last baseline — so a prompt edit that quietly " +
      "degrades quality gets caught before it merges.",
    metrics: [
      { value: "golden", label: "dataset diffing" },
      { value: "v1 → v2", label: "prompt versioning" },
    ],
    repo: "https://github.com/larachieppe/model-regression-detector",
    caseStudy: {
      problem:
        "A one-line prompt edit can quietly degrade output quality and sail through review, because " +
        "nothing in a normal CI pipeline understands LLM outputs. I wanted regression testing for prompts.",
      flow: [
        { label: "Golden set", sub: "labeled cases" },
        { label: "Run", sub: "versioned prompt" },
        { label: "Score", sub: "multi-dimension" },
        { label: "Diff", sub: "vs. last baseline" },
        { label: "Gate", sub: "block + alert" },
      ],
      decision: {
        title: "Diff every run against a versioned baseline",
        body:
          "The feature under test is an email classifier with a typed interface. Each prompt " +
          "version runs against a golden dataset, outputs are scored on multiple dimensions, and " +
          "the run is diffed against the last baseline — so a quality regression becomes a visible " +
          "diff that can block a merge and page a channel, rather than a silent drift in production.",
      },
      result:
        "A versioned, testable contract around prompt changes — the same discipline as CI/CD, " +
        "applied to the part of an LLM system that usually has none.",
    },
  },
];

export const experience = [
  {
    company: "Reach Capital",
    role: "Product Manager & Software Engineer (Contract)",
    dates: "Aug 2025 — Present",
    place: "Berkeley, CA",
    stack: "SQL · Supabase · React",
    points: [
      "Engineered infrastructure empowering 130+ partner companies to analyze student applications.",
      "Developed dynamic, parameterized SQL filters and optimized Supabase schema design, cutting latency by 45%.",
      "Directed a team of 6 through 5+ sprints, delivering 5 production releases and launching 10 features.",
    ],
  },
  {
    company: "BTG Pactual",
    role: "Software Engineering Intern",
    dates: "Jan 2025 — Sept 2025",
    place: "São Paulo, Brazil",
    stack: "AWS · Kotlin · MongoDB",
    points: [
      "Optimized MongoDB aggregation queries for account filtering, reducing query latency by 50%.",
      "Built an AWS SNS → SQS pipeline automating fraud-signal delivery, enabling real-time revocation across 4 payment microservices.",
      "Streamlined account sign-in by detecting and reusing existing accounts, improving completion rate by 25%.",
    ],
  },
  {
    company: "Lafayette Square",
    role: "Product Manager & Software Engineer (Contract)",
    dates: "Jan 2025 — Sept 2025",
    place: "Berkeley, CA",
    stack: "AWS · MongoDB · React Native",
    points: [
      "Built and deployed a React Native app serving financial insights to 34+ client companies alongside the CEO and CTO.",
      "Led a cross-functional team of 10 through 10+ weeks of agile sprints, improving release cadence by 40%.",
      "Implemented dynamic parametrized queries delivering real-time, interactive data from AWS-hosted MongoDB.",
    ],
  },
  {
    company: "SUR",
    role: "Software Engineer (Contract)",
    dates: "Jan 2025 — Aug 2025",
    place: "Berkeley, CA",
    stack: "AWS · GraphQL · React Native",
    points: [
      "Developed and deployed a scalable car rental feature in a fleet management app serving 5,000+ users.",
      "Integrated GraphQL APIs with an AWS backend to streamline fleet inventory storage and retrieval.",
      "Reduced data query latency by 25% through GraphQL caching and AWS API Gateway optimization.",
    ],
  },
  {
    company: "UC Berkeley EECS",
    role: "Teaching Intern — Data Structures & Algorithms (CS61B)",
    dates: "Aug 2024 — Dec 2024",
    place: "Berkeley, CA",
    stack: "Java",
    points: [
      "One of 20 teaching interns supporting 1,500+ students.",
      "Guided students through object-oriented programming, algorithms and data structures in Java.",
      "Resolved 50+ student tickets covering asymptotics, sorting, hashing and percolation simulations.",
    ],
  },
];

export const skills = [
  {
    group: "Languages",
    items: ["Python", "Java", "Kotlin", "TypeScript", "JavaScript", "C", "C++", "C#", "SQL", "GraphQL"],
  },
  {
    group: "AI / ML",
    items: ["PyTorch", "HuggingFace", "Transformers", "LangGraph", "Claude API", "scikit-learn", "Pandas", "NumPy", "Matplotlib"],
  },
  {
    group: "Frameworks",
    items: ["React Native", "Next.js", "Node.js", "Express.js", "FastAPI", "Redux"],
  },
  {
    group: "Infrastructure",
    items: ["AWS (S3, SNS, SQS, Lambda, API Gateway)", "PostgreSQL", "MongoDB", "DynamoDB", "Drizzle", "Git", "Postman"],
  },
  {
    group: "Spoken",
    items: ["English (fluent)", "Portuguese (native)", "German (B2)", "Spanish (B2)"],
  },
];

// Section registry — drives the side rail and the 3D morph targets.
export const sections = [
  { id: "hero", label: "Index", shape: "transformer" },
  { id: "about", label: "About", shape: "transformer" },
  { id: "lab", label: "Live", shape: "transformer" },
  { id: "work", label: "Work", shape: "network" },
  { id: "experience", label: "Experience", shape: "network" },
  { id: "skills", label: "Skills", shape: "globe" },
  { id: "contact", label: "Contact", shape: "globe" },
];
